# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme: "mmistakes/minimal-mistakes"

title: Josh Michaels Site Title
email: your-email@example.com
description: "Site description"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
words_per_minute: 200
permalink: pretty # Remove page extention form url in browser
data_dir: _data


author_profile: true
# settings for author profile
author:
  name   : "Josh Michaels"
  avatar : "/assets/images/image.png"
  bio    : "AI, CS, Game Dev, Plants"
  location: "NJ"
  social:
    github: JoshM483
    linkedin: https://www.linkedin.com/in/joshuaemichaels
    email: michaelsjoshua@gmail.com




include:
  - _pages
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme
  - jekyll-include-cache


# Font Matter Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false

